on: push
name: deploy 
jobs:
        deploy:
                name: publish to dockerhub
                runs-on: ubuntu-latest
                steps:
                        - name: checkout code
                          uses: actions/checkout@v2
                        - name: Set up JDK 11
                          uses: actions/setup-java@v2
                          with:
                                java-version: '11'
                                distribution: 'adopt'
                                cache: maven
                        - name: build jar
                          run: mvn -B package --file pom.xml
                        #- name: docker login
                        #  run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
                        - name: Build the Docker images y push
                        #  run: docker build . --tag alexander96pz/pruebas
                        #- name: publish to dockerhub
                        #  run: docker push ${{secrets.DOCKERHUB_USERNAME}}/pruebas
                        #  tag_with_ref: true
                          
                          uses: docker/build-push-action@v1
                          with:
                                 username: ${{ secrets.DOCKERHUB_USERNAME }}
                                 password: ${{ secrets.DOCKERHUB_PASSWORD }}
                                 # repository: alexander96pz/pruebaci
                                 repository: alexander96pz/pruebas
