on: push
name: deploy 
jobs:
        deploy:
                name: publish to dockerhub
                runs-on: ubuntu-latest
                steps:
                        - name: checkout code
                          uses: actions/checkout@v2
                        - name: docker login
                          run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
                        - name: Build the Docker images
                          run: docker build . --file Dockerfile --tag alexander96pz/pruebas
                        - name: publish to dockerhub
                          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/pruebas
                          #         uses: docker/build-push-action@v1
                          #with:
                          #       username: ${{ secrets.DOCKERHUB_USERNAME }}
                          #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
                          #       repository: alexander96pz/pruebaci
                          #tags: ${{ github.sha }}
