on:
        push:
                branches: 'main'
name: deploy 
jobs:
        deploy:
                name: publish to dockerhub
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@master
                        - name: build to push to dockerhub
                          uses: docker/build-push-action@v2
                          with:
                                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
                                  repository: ${{ github.repository }}
                                  tag_with_ref: true
                                  tag_with_sha: true
                                  tags: ${{ github.sha }}
