on: push
name: deploy 
jobs:
        deploy:
                name: publish to dockerhub
                runs-on: ubuntu-latest
                steps:
                        - name: checkout code
                          uses: actions/checkout@v2
                        - name: publish to dockerhub
                          uses: docker/build-push-action@v1
                          with:
                                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
                                  repository: alexander96pz/pruebaci
                                  tag_with_ref: true
                                  tag_with_sha: true
                                  tags: ${{ github.sha }}
